config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'
  root :to => "welcome#index"
  resources :libraties
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
validates :name, presence: true,
				 length: {minimum: 5}
end

app/models/libraty.rb
class Libraty < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 def new
 end
 
 def create
 		
 end	
end

app/controllers/libraties_controller.rb
class LibratiesController < ApplicationController
  before_action :set_libraty, only: [:show, :edit, :update, :destroy]

  # GET /libraties
  # GET /libraties.json
  def index
    @libraties = Libraty.all
  end

  # GET /libraties/1
  # GET /libraties/1.json
  def show
  end

  # GET /libraties/new
  def new
    @libraty = Libraty.new
  end

  # GET /libraties/1/edit
  def edit
  end

  # POST /libraties
  # POST /libraties.json
  def create
    @libraty = Libraty.new(libraty_params)

    respond_to do |format|
      if @libraty.save
        format.html { redirect_to @libraty, notice: 'Libraty was successfully created.' }
        format.json { render :show, status: :created, location: @libraty }
      else
        format.html { render :new }
        format.json { render json: @libraty.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /libraties/1
  # PATCH/PUT /libraties/1.json
  def update
    respond_to do |format|
      if @libraty.update(libraty_params)
        format.html { redirect_to @libraty, notice: 'Libraty was successfully updated.' }
        format.json { render :show, status: :ok, location: @libraty }
      else
        format.html { render :edit }
        format.json { render json: @libraty.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /libraties/1
  # DELETE /libraties/1.json
  def destroy
    @libraty.destroy
    respond_to do |format|
      format.html { redirect_to libraties_url, notice: 'Libraty was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_libraty
      @libraty = Libraty.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def libraty_params
      params.require(:libraty).permit(:name, :Pnumber)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraties_helper.rb
module LibratiesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Work</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraties/_form.html.erb
<%= form_with(model: libraty, local: true) do |form| %>
  <% if libraty.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(libraty.errors.count, "error") %> prohibited this libraty from being saved:</h2>

      <ul>
      <% libraty.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :libraty_name %>
  </div>

  <div class="field">
    <%= form.label :Pnumber %>
    <%= form.number_field :Pnumber, id: :libraty_Pnumber %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/libraties/edit.html.erb
<h1>Editing Libraty</h1>

<%= render 'form', libraty: @libraty %>

<%= link_to 'Show', @libraty %> |
<%= link_to 'Back', libraties_path %>

app/views/libraties/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Libraties</h1>
<%= link_to 'home', new_libraty_path %>
<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Pnumber</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @libraties.each do |libraty| %>
      <tr>
        <td><%= libraty.name %></td>
        <td><%= libraty.Pnumber %></td>
        <td><%= link_to 'Show', libraty %></td>
        <td><%= link_to 'Edit', edit_libraty_path(libraty) %></td>
        <td><%= link_to 'Destroy', libraty, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Libraty', new_libraty_path %>

app/views/libraties/new.html.erb
<h1>New Libraty</h1>

<%= render 'form', libraty: @libraty %>

<%= link_to 'Back', libraties_path %>

<%= form_for :libraty, url: libraties_path do |f| %>
  
<% end %>
 
<%= link_to 'Back', libraties_path %>

app/views/libraties/show.html.erb
w<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @libraty.name %>
</p>

<p>
  <strong>Pnumber:</strong>
  <%= @libraty.Pnumber %>
</p>

<%= link_to 'Edit', edit_libraty_path(@libraty) %> |
<%= link_to 'Back', libraties_path %>

app/views/welcome/index.html.erb
<h1>hola mundo</h1>

<p><%= link_to 'my blog', controller: 'libraties'%></p>